FROM osrf/ros:noetic-desktop-full@sha256:7dbfb9576d8e6d226c31e06129a82aaab8702695f38eca2116918cb9b9308797

ARG DEBIAN_FRONTEND=noninteractive
ARG USERNAME=ros
ARG USER_UID=1000
ARG USER_GID=1000
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 TZ=Etc/UTC

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates git build-essential cmake ccache pkg-config \
    python3-pip python3-rosdep python3-vcstool python3-yaml python3-gdal \
    python3-numpy python3-pandas python3-tqdm python3-shapely python3-tk \
    python3-catkin-tools \
    libboost-all-dev libarmadillo-dev libmetis-dev libgdal-dev gdal-bin \
    libgeographic-dev zip unzip jq procps coreutils \
    ros-noetic-geometry2 ros-noetic-tf2-sensor-msgs ros-noetic-rosunit \
    ros-noetic-rostest ros-noetic-topic-tools \
 && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --no-cache-dir 'descartes==1.1.0'

RUN if ! getent group ${USER_GID} >/dev/null; then groupadd --gid ${USER_GID} ${USERNAME}; fi \
 && if ! id -u ${USERNAME} >/dev/null 2>&1; then useradd --uid ${USER_UID} --gid ${USER_GID} -m -s /bin/bash ${USERNAME}; fi

USER ${USERNAME}
RUN echo 'source /opt/ros/noetic/setup.bash' >> /home/${USERNAME}/.bashrc
WORKDIR /work
CMD ["bash"]
