FROM ros:jazzy-ros-base-noble

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    git \
    python3-colcon-common-extensions \
    python3-rosdep \
    python3-vcstool \
    libgeographiclib-dev \
    ros-jazzy-ament-cmake-gtest \
 && rm -rf /var/lib/apt/lists/*

SHELL ["/bin/bash", "-lc"]
WORKDIR /work
CMD ["bash"]
