FROM osrf/ros:jazzy-desktop-full
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends build-essential cmake git python3-colcon-common-extensions python3-rosdep libgeographiclib-dev libeigen3-dev libboost-all-dev ros-jazzy-navigation2 ros-jazzy-nav2-bringup ros-jazzy-ros-gz && rm -rf /var/lib/apt/lists/*
WORKDIR /ws
CMD ["bash"]
